import {
  ComponentNode,
  CONTAINER_TYPE,
  PageNode,
  SectionNode,
  SECTION_POSITION,
} from "@/redux/currentApp/editor/components/componentsState"

export const BASIC_BODY_SECTION_CONFIG: SectionNode = {
  displayName: "bodySection",
  parentNode: "page1",
  showName: "bodySection",
  isDragging: false,
  isResizing: false,
  type: "SECTION_NODE",
  containerType: CONTAINER_TYPE.EDITOR_DOT_PANEL,
  verticalResize: true,
  h: 0,
  w: 0,
  minH: 0,
  minW: 0,
  unitW: 0,
  unitH: 0,
  x: -1,
  y: -1,
  z: 0,
  props: {
    currentViewIndex: 0,
    viewSortedKey: ["bodyContainer1"],
  },
  childrenNode: [
    {
      displayName: "bodyContainer1",
      parentNode: "bodySection",
      showName: "bodyContainer",
      isDragging: false,
      isResizing: false,
      type: "DOT_PANEL",
      containerType: CONTAINER_TYPE.EDITOR_DOT_PANEL,
      verticalResize: true,
      h: 0,
      w: 0,
      minH: 0,
      minW: 0,
      unitW: 0,
      unitH: 0,
      x: -1,
      y: -1,
      z: 0,
      childrenNode: [],
      props: {},
    },
  ],
}

export const BASIC_LEFT_SECTION_CONFIG: SectionNode = {
  displayName: "leftSection",
  parentNode: "page1",
  showName: "leftSection",
  isDragging: false,
  isResizing: false,
  type: "SECTION_NODE",
  containerType: CONTAINER_TYPE.EDITOR_DOT_PANEL,
  verticalResize: true,
  h: 0,
  w: 0,
  minH: 0,
  minW: 0,
  unitW: 0,
  unitH: 0,
  x: -1,
  y: -1,
  z: 0,
  props: {
    currentViewIndex: 0,
    viewSortedKey: ["leftContainer1"],
  },
  childrenNode: [
    {
      displayName: "leftContainer1",
      parentNode: "leftSection",
      showName: "leftContainer",
      isDragging: false,
      isResizing: false,
      type: "DOT_PANEL",
      containerType: CONTAINER_TYPE.EDITOR_DOT_PANEL,
      verticalResize: true,
      h: 0,
      w: 0,
      minH: 0,
      minW: 0,
      unitW: 0,
      unitH: 0,
      x: -1,
      y: -1,
      z: 0,
      childrenNode: [],
      props: {},
    },
  ],
}

export const BASIC_RIGHT_SECTION_CONFIG: SectionNode = {
  displayName: "rightSection",
  parentNode: "page1",
  showName: "rightSection",
  isDragging: false,
  isResizing: false,
  type: "SECTION_NODE",
  containerType: CONTAINER_TYPE.EDITOR_DOT_PANEL,
  verticalResize: true,
  h: 0,
  w: 0,
  minH: 0,
  minW: 0,
  unitW: 0,
  unitH: 0,
  x: -1,
  y: -1,
  z: 0,
  props: {
    currentViewIndex: 0,
    viewSortedKey: ["rightContainer1"],
  },
  childrenNode: [
    {
      displayName: "rightContainer1",
      parentNode: "rightSection",
      showName: "rightContainer",
      isDragging: false,
      isResizing: false,
      type: "DOT_PANEL",
      containerType: CONTAINER_TYPE.EDITOR_DOT_PANEL,
      verticalResize: true,
      h: 0,
      w: 0,
      minH: 0,
      minW: 0,
      unitW: 0,
      unitH: 0,
      x: -1,
      y: -1,
      z: 0,
      childrenNode: [],
      props: {},
    },
  ],
}

export const BASIC_HEADER_SECTION_CONFIG: SectionNode = {
  displayName: "headerSection",
  parentNode: "page1",
  showName: "headerSection",
  isDragging: false,
  isResizing: false,
  type: "SECTION_NODE",
  containerType: CONTAINER_TYPE.EDITOR_DOT_PANEL,
  verticalResize: true,
  h: 0,
  w: 0,
  minH: 0,
  minW: 0,
  unitW: 0,
  unitH: 0,
  x: -1,
  y: -1,
  z: 0,
  props: {
    currentViewIndex: 0,
    viewSortedKey: ["headerContainer1"],
  },
  childrenNode: [
    {
      displayName: "headerContainer1",
      parentNode: "headerSection",
      showName: "headerContainer",
      isDragging: false,
      isResizing: false,
      type: "DOT_PANEL",
      containerType: CONTAINER_TYPE.EDITOR_DOT_PANEL,
      verticalResize: true,
      h: 0,
      w: 0,
      minH: 0,
      minW: 0,
      unitW: 0,
      unitH: 0,
      x: -1,
      y: -1,
      z: 0,
      childrenNode: [],
      props: {},
    },
  ],
}

export const BASIC_FOOTER_SECTION_CONFIG: SectionNode = {
  displayName: "footerSection",
  parentNode: "page1",
  showName: "footerSection",
  isDragging: false,
  isResizing: false,
  type: "SECTION_NODE",
  containerType: CONTAINER_TYPE.EDITOR_DOT_PANEL,
  verticalResize: true,
  h: 0,
  w: 0,
  minH: 0,
  minW: 0,
  unitW: 0,
  unitH: 0,
  x: -1,
  y: -1,
  z: 0,
  props: {
    currentViewIndex: 0,
    viewSortedKey: ["footerContainer1"],
  },
  childrenNode: [
    {
      displayName: "footerContainer1",
      parentNode: "footerSection",
      showName: "footerContainer",
      isDragging: false,
      isResizing: false,
      type: "DOT_PANEL",
      containerType: CONTAINER_TYPE.EDITOR_DOT_PANEL,
      verticalResize: true,
      h: 0,
      w: 0,
      minH: 0,
      minW: 0,
      unitW: 0,
      unitH: 0,
      x: -1,
      y: -1,
      z: 0,
      childrenNode: [],
      props: {},
    },
  ],
}

export const DEFAULT_PAGE_LAYOUT_CONFIG: PageNode[] = [
  {
    displayName: "page1",
    parentNode: "root",
    showName: "page",
    isDragging: false,
    isResizing: false,
    type: "PAGE_NODE",
    containerType: CONTAINER_TYPE.EDITOR_DOT_PANEL,
    verticalResize: true,
    h: 0,
    w: 0,
    minH: 0,
    minW: 0,
    unitW: 0,
    unitH: 0,
    x: -1,
    y: -1,
    z: 0,
    props: {
      canvasSize: "responsive",
      canvasWidth: "auto",
      layout: "default",
      leftPosition: SECTION_POSITION.NONE,
      rightPosition: SECTION_POSITION.NONE,
      hasFooter: false,
      hasHeader: false,
      hasLeft: false,
      hasRight: false,
      leftWidth: 0,
      rightWidth: 0,
      topHeight: 0,
      bottomHeight: 0,
      isLeftFixed: true,
      isRightFixed: true,
      isHeaderFixed: true,
      isFooterFixed: true,
    },
    childrenNode: [BASIC_BODY_SECTION_CONFIG],
  },
]

export const PRESET_A_PAGE_LAYOUT_CONFIG: PageNode[] = [
  {
    displayName: "page1",
    parentNode: "root",
    showName: "page",
    isDragging: false,
    isResizing: false,
    type: "PAGE_NODE",
    containerType: CONTAINER_TYPE.EDITOR_DOT_PANEL,
    verticalResize: true,
    h: 0,
    w: 0,
    minH: 0,
    minW: 0,
    unitW: 0,
    unitH: 0,
    x: -1,
    y: -1,
    z: 0,
    props: {
      canvasSize: "responsive",
      canvasWidth: "auto",
      layout: "presetA",
      leftPosition: SECTION_POSITION.FULL,
      rightPosition: SECTION_POSITION.NONE,
      hasFooter: false,
      hasHeader: false,
      hasLeft: true,
      hasRight: false,
      leftWidth: 20,
      rightWidth: 0,
      topHeight: 0,
      bottomHeight: 0,
      isLeftFixed: true,
      isRightFixed: true,
      isHeaderFixed: true,
      isFooterFixed: true,
    },
    childrenNode: [BASIC_LEFT_SECTION_CONFIG, BASIC_BODY_SECTION_CONFIG],
  },
]

export const PRESET_B_PAGE_LAYOUT_CONFIG: ComponentNode[] = [
  {
    displayName: "page1",
    parentNode: "root",
    showName: "page",
    isDragging: false,
    isResizing: false,
    type: "PAGE_NODE",
    containerType: CONTAINER_TYPE.EDITOR_DOT_PANEL,
    verticalResize: true,
    h: 0,
    w: 0,
    minH: 0,
    minW: 0,
    unitW: 0,
    unitH: 0,
    x: -1,
    y: -1,
    z: 0,
    props: {
      canvasSize: "responsive",
      canvasWidth: "auto",
      layout: "presetB",
      leftPosition: "NONE",
      rightPosition: "NONE",
      hasFooter: true,
      hasHeader: true,
      hasLeft: false,
      hasRight: false,
      leftWidth: 0,
      rightWidth: 0,
      topHeight: 96,
      bottomHeight: 96,
      isLeftFixed: true,
      isRightFixed: true,
      isHeaderFixed: true,
      isFooterFixed: true,
    },
    childrenNode: [
      BASIC_HEADER_SECTION_CONFIG,
      BASIC_BODY_SECTION_CONFIG,
      BASIC_FOOTER_SECTION_CONFIG,
    ],
  },
]

export const PRESET_C_PAGE_LAYOUT_CONFIG: PageNode[] = [
  {
    displayName: "page1",
    parentNode: "root",
    showName: "page",
    isDragging: false,
    isResizing: false,
    type: "PAGE_NODE",
    containerType: CONTAINER_TYPE.EDITOR_DOT_PANEL,
    verticalResize: true,
    h: 0,
    w: 0,
    minH: 0,
    minW: 0,
    unitW: 0,
    unitH: 0,
    x: -1,
    y: -1,
    z: 0,
    props: {
      canvasSize: "responsive",
      canvasWidth: "auto",
      layout: "presetC",
      leftPosition: SECTION_POSITION.BOTTOM,
      rightPosition: SECTION_POSITION.NONE,
      hasFooter: true,
      hasHeader: true,
      hasLeft: true,
      hasRight: false,
      leftWidth: 20,
      rightWidth: 0,
      topHeight: 96,
      bottomHeight: 96,
      isLeftFixed: true,
      isRightFixed: true,
      isHeaderFixed: true,
      isFooterFixed: true,
    },
    childrenNode: [
      BASIC_HEADER_SECTION_CONFIG,
      BASIC_LEFT_SECTION_CONFIG,
      BASIC_BODY_SECTION_CONFIG,
      BASIC_FOOTER_SECTION_CONFIG,
    ],
  },
]

export const PRESET_D_PAGE_LAYOUT_CONFIG: PageNode[] = [
  {
    displayName: "page1",
    parentNode: "root",
    showName: "page",
    isDragging: false,
    isResizing: false,
    type: "PAGE_NODE",
    containerType: CONTAINER_TYPE.EDITOR_DOT_PANEL,
    verticalResize: true,
    h: 0,
    w: 0,
    minH: 0,
    minW: 0,
    unitW: 0,
    unitH: 0,
    x: -1,
    y: -1,
    z: 0,
    props: {
      canvasSize: "responsive",
      canvasWidth: "auto",
      layout: "presetD",
      leftPosition: SECTION_POSITION.BOTTOM,
      rightPosition: SECTION_POSITION.BOTTOM,
      hasFooter: true,
      hasHeader: true,
      hasLeft: true,
      hasRight: true,
      leftWidth: 20,
      rightWidth: 20,
      topHeight: 96,
      bottomHeight: 96,
      isLeftFixed: true,
      isRightFixed: true,
      isHeaderFixed: true,
      isFooterFixed: true,
    },
    childrenNode: [
      BASIC_HEADER_SECTION_CONFIG,
      BASIC_RIGHT_SECTION_CONFIG,
      BASIC_LEFT_SECTION_CONFIG,
      BASIC_BODY_SECTION_CONFIG,
      BASIC_FOOTER_SECTION_CONFIG,
    ],
  },
]

export const PRESET_E_PAGE_LAYOUT_CONFIG: PageNode[] = [
  {
    displayName: "page1",
    parentNode: "root",
    showName: "page",
    isDragging: false,
    isResizing: false,
    type: "PAGE_NODE",
    containerType: CONTAINER_TYPE.EDITOR_DOT_PANEL,
    verticalResize: true,
    h: 0,
    w: 0,
    minH: 0,
    minW: 0,
    unitW: 0,
    unitH: 0,
    x: -1,
    y: -1,
    z: 0,
    props: {
      canvasSize: "responsive",
      canvasWidth: "auto",
      layout: "presetE",
      leftPosition: SECTION_POSITION.FULL,
      rightPosition: SECTION_POSITION.NONE,
      hasFooter: true,
      hasHeader: true,
      hasLeft: true,
      hasRight: false,
      leftWidth: 20,
      rightWidth: 20,
      topHeight: 96,
      bottomHeight: 96,
      isLeftFixed: true,
      isRightFixed: true,
      isHeaderFixed: true,
      isFooterFixed: true,
    },
    childrenNode: [
      BASIC_HEADER_SECTION_CONFIG,
      BASIC_LEFT_SECTION_CONFIG,
      BASIC_BODY_SECTION_CONFIG,
      BASIC_FOOTER_SECTION_CONFIG,
    ],
  },
]

export const BASIC_APP_CONFIG: PageNode[] = [
  {
    displayName: "page1",
    parentNode: "root",
    showName: "page",
    isDragging: false,
    isResizing: false,
    type: "PAGE_NODE",
    containerType: CONTAINER_TYPE.EDITOR_DOT_PANEL,
    verticalResize: true,
    h: 0,
    w: 0,
    minH: 0,
    minW: 0,
    unitW: 0,
    unitH: 0,
    x: -1,
    y: -1,
    z: 0,
    props: {
      canvasSize: "responsive",
      canvasWidth: "auto",
      layout: "default",
      leftPosition: SECTION_POSITION.NONE,
      rightPosition: SECTION_POSITION.NONE,
      hasFooter: false,
      hasHeader: false,
      hasLeft: false,
      hasRight: false,
      leftWidth: 0,
      rightWidth: 0,
      topHeight: 0,
      bottomHeight: 0,
      isLeftFixed: true,
      isRightFixed: true,
      isHeaderFixed: true,
      isFooterFixed: true,
    },
    childrenNode: [
      BASIC_HEADER_SECTION_CONFIG,
      BASIC_RIGHT_SECTION_CONFIG,
      BASIC_LEFT_SECTION_CONFIG,
      BASIC_BODY_SECTION_CONFIG,
      BASIC_FOOTER_SECTION_CONFIG,
    ],
  },
]

export const layoutValueMapConfig = {
  default: DEFAULT_PAGE_LAYOUT_CONFIG,
  presetA: PRESET_A_PAGE_LAYOUT_CONFIG,
  presetB: PRESET_B_PAGE_LAYOUT_CONFIG,
  presetC: PRESET_C_PAGE_LAYOUT_CONFIG,
  presetD: PRESET_D_PAGE_LAYOUT_CONFIG,
  presetE: PRESET_E_PAGE_LAYOUT_CONFIG,
}

export const sectionNameMapConfig = {
  leftSection: BASIC_LEFT_SECTION_CONFIG,
  rightSection: BASIC_RIGHT_SECTION_CONFIG,
  headerSection: BASIC_HEADER_SECTION_CONFIG,
  footerSection: BASIC_FOOTER_SECTION_CONFIG,
}
