export const BASIC_APP_CONFIG = [
  {
    displayName: "page1",
    parentNode: "root",
    showName: "page",
    error: false,
    isDragging: false,
    isResizing: false,
    type: "PAGE_NODE",
    containerType: "EDITOR_DOT_PANEL",
    verticalResize: true,
    h: 0,
    w: 0,
    minH: 0,
    minW: 0,
    unitW: 0,
    unitH: 0,
    x: -1,
    y: -1,
    z: 0,
    props: {
      canvasSize: "auto",
      canvasWidth: "auto",
      layout: "presetE",
      leftPosition: "CENTER",
      rightPosition: "CENTER",
      hasFooter: true,
      hasHeader: true,
      hasLeft: true,
      hasRight: true,
      leftWidth: 20,
      rightWidth: 20,
      topHeight: 96,
      bottomHeight: 96,
    },
    panelConfig: null,
    childrenNode: [
      {
        displayName: "headerSection",
        parentNode: "page1",
        showName: "headerSection",
        error: false,
        isDragging: false,
        isResizing: false,
        type: "SECTION_NODE",
        containerType: "EDITOR_DOT_PANEL",
        verticalResize: true,
        h: 0,
        w: 0,
        minH: 0,
        minW: 0,
        unitW: 0,
        unitH: 0,
        x: -1,
        y: -1,
        z: 0,
        props: {
          currentViewIndex: 0,
          viewSortedKey: ["headerContainer1"],
        },
        panelConfig: null,
        childrenNode: [
          {
            displayName: "headerContainer1",
            parentNode: "headerSection",
            showName: "headerContainer",
            error: false,
            isDragging: false,
            isResizing: false,
            type: "DOT_PANEL",
            containerType: "EDITOR_DOT_PANEL",
            verticalResize: true,
            h: 0,
            w: 0,
            minH: 0,
            minW: 0,
            unitW: 0,
            unitH: 0,
            x: -1,
            y: -1,
            z: 0,
          },
        ],
      },
      {
        displayName: "rightSection",
        parentNode: "page1",
        showName: "rightSection",
        error: false,
        isDragging: false,
        isResizing: false,
        type: "SECTION_NODE",
        containerType: "EDITOR_DOT_PANEL",
        verticalResize: true,
        h: 0,
        w: 0,
        minH: 0,
        minW: 0,
        unitW: 0,
        unitH: 0,
        x: -1,
        y: -1,
        z: 0,
        props: {
          currentViewIndex: 0,
          viewSortedKey: ["rightContainer1"],
        },
        panelConfig: null,
        childrenNode: [
          {
            displayName: "rightContainer1",
            parentNode: "rightSection",
            showName: "rightContainer",
            error: false,
            isDragging: false,
            isResizing: false,
            type: "DOT_PANEL",
            containerType: "EDITOR_DOT_PANEL",
            verticalResize: true,
            h: 0,
            w: 0,
            minH: 0,
            minW: 0,
            unitW: 0,
            unitH: 0,
            x: -1,
            y: -1,
            z: 0,
          },
        ],
      },
      {
        displayName: "leftSection",
        parentNode: "page1",
        showName: "leftSection",
        error: false,
        isDragging: false,
        isResizing: false,
        type: "SECTION_NODE",
        containerType: "EDITOR_DOT_PANEL",
        verticalResize: true,
        h: 0,
        w: 0,
        minH: 0,
        minW: 0,
        unitW: 0,
        unitH: 0,
        x: -1,
        y: -1,
        z: 0,
        props: {
          currentViewIndex: 0,
          viewSortedKey: ["leftContainer1"],
        },
        panelConfig: null,
        childrenNode: [
          {
            displayName: "leftContainer1",
            parentNode: "leftSection",
            showName: "leftContainer",
            error: false,
            isDragging: false,
            isResizing: false,
            type: "DOT_PANEL",
            containerType: "EDITOR_DOT_PANEL",
            verticalResize: true,
            h: 0,
            w: 0,
            minH: 0,
            minW: 0,
            unitW: 0,
            unitH: 0,
            x: -1,
            y: -1,
            z: 0,
          },
        ],
      },
      {
        displayName: "bodySection",
        parentNode: "page1",
        showName: "bodySection",
        error: false,
        isDragging: false,
        isResizing: false,
        type: "SECTION_NODE",
        containerType: "EDITOR_DOT_PANEL",
        verticalResize: true,
        h: 0,
        w: 0,
        minH: 0,
        minW: 0,
        unitW: 0,
        unitH: 0,
        x: -1,
        y: -1,
        z: 0,
        props: {
          currentViewIndex: 0,
          viewSortedKey: ["bodyContainer1"],
        },
        panelConfig: null,
        childrenNode: [
          {
            displayName: "bodyContainer1",
            parentNode: "bodySection",
            showName: "bodyContainer",
            error: false,
            isDragging: false,
            isResizing: false,
            type: "DOT_PANEL",
            containerType: "EDITOR_DOT_PANEL",
            verticalResize: true,
            h: 0,
            w: 0,
            minH: 0,
            minW: 0,
            unitW: 0,
            unitH: 0,
            x: -1,
            y: -1,
            z: 0,
          },
        ],
      },
      {
        displayName: "footerSection",
        parentNode: "page1",
        showName: "footerSection",
        error: false,
        isDragging: false,
        isResizing: false,
        type: "SECTION_NODE",
        containerType: "EDITOR_DOT_PANEL",
        verticalResize: true,
        h: 0,
        w: 0,
        minH: 0,
        minW: 0,
        unitW: 0,
        unitH: 0,
        x: -1,
        y: -1,
        z: 0,
        props: {
          currentViewIndex: 0,
          viewSortedKey: ["footerContainer1"],
        },
        panelConfig: null,
        childrenNode: [
          {
            displayName: "footerContainer1",
            parentNode: "footerSection",
            showName: "footerContainer",
            error: false,
            isDragging: false,
            isResizing: false,
            type: "DOT_PANEL",
            containerType: "EDITOR_DOT_PANEL",
            verticalResize: true,
            h: 0,
            w: 0,
            minH: 0,
            minW: 0,
            unitW: 0,
            unitH: 0,
            x: -1,
            y: -1,
            z: 0,
          },
        ],
      },
    ],
  },
]
