organization: ILLA Cloud
defaultSticker: clnbuq0zt55350il7di08vxey
stickers:
  -
    id: clnbuwccz20050il45drk120o
    alias: HACKTOBERFEST-ACCEPTED
  -
   id: clnbuz74g85880lkz0a5fyzis
   alias: HACKTOBERFEST-ACCEPTED
  -
    id: clnbv3uo903310fmgagvt713t
    alias: HACKTOBERFEST-ACCEPTED
  -
   id: clnbuq0zt55350il7di08vxey
   alias: HACKTOBERFEST-ACCEPTED
