organization: illa
defaultSticker: clnbuq0zt55350il7di08vxey
stickers:
  -
    id: clnbuwccz20050il45drk120o
    alias: Awesome ILLA App
  -
   id: clnbuz74g85880lkz0a5fyzis
   alias: Awesome AI Agent
  -
    id: clnbv3uo903310fmgagvt713t
    alias: AI Agent
  -
   id: clnbuq0zt55350il7di08vxey
   alias: ILLA App
