import {
  HorizontalStartIcon,
  HorizontalEndIcon,
  HorizontalCenterIcon,
  HorizontalFullIcon,
} from "@illa-design/icon"
import { PanelConfig } from "@/page/App/components/InspectPanel/interface"
import { colorSchemeOptions } from "@/widgetLibrary/PublicSector/colorSchemeOptions"

import { VALIDATION_TYPES } from "@/utils/validationFactory"

export const UPLOAD_PANEL_CONFIG: PanelConfig[] = [
  {
    id: "upload-basic",
    groupName: "editor.inspect.setter_group.basic",
    children: [
      {
        id: "upload-basic-text",
        labelName: "editor.inspect.setter_label.text",
        attrName: "text",
        setterType: "INPUT_SETTER",
        expectedType: VALIDATION_TYPES.STRING,
      },
      {
        id: "upload-basic-fileTypes",
        labelName: "editor.inspect.setter_label.file_types",
        attrName: "value",
        setterType: "INPUT_SETTER",
        expectedType: VALIDATION_TYPES.ARRAY,
      },
      {
        id: "upload-basic-selectionType",
        labelName: "editor.inspect.setter_label.selection_type",
        attrName: "value",
        setterType: "BASE_SELECT_SETTER",
        expectedType: VALIDATION_TYPES.STRING,
      },
      {
        id: "upload-basic-fileList",
        labelName: "editor.inspect.setter_label.file_list",
        attrName: "value",
        setterType: "SWITCH_SETTER",
        expectedType: VALIDATION_TYPES.BOOLEAN,
      },
    ],
  },
  {
    id: "upload-interaction",
    groupName: "editor.inspect.setter_group.interaction",
    children: [
      {
        id: "upload-interaction-event-handler",
        attrName: "events",
        labelName: "editor.inspect.setter_label.event_handler",
        labelDesc: "xxxxx",
        setterType: "EVENT_HANDLER_SETTER",
        useCustomLayout: true,
        childrenSetter: [
          {
            id: "event",
            labelName: "editor.inspect.setter_label.event",
            setterType: "BASE_SELECT_SETTER",
            attrName: "eventType",
            options: [{ label: "Change", value: "onChange" }],
          },
          {
            id: "action",
            labelName: "editor.inspect.setter_label.action",
            setterType: "EVENT_ACTION_SELECT_SETTER",
            attrName: "actionType",
            options: [
              {
                labelName: "editor.inspect.setter_label.trigger_query",
                value: "datasource",
              },
              {
                labelName: "editor.inspect.setter_label.control_component",
                value: "widget",
              },
              {
                label: "editor.inspect.setter_label.run_script",
                value: "script",
              },
              {
                label: "editor.inspect.setter_label.go_to_url",
                value: "openUrl",
              },
              {
                label: "editor.inspect.setter_label.show_notification",
                value: "showNotification",
              },
            ],
          },
          {
            id: "query",
            labelName: "Query",
            setterType: "BASE_SELECT_SETTER",
            attrName: "queryID",
            bindAttrName: "actionType",
            shown: (type) => type === "datasource",
            options: [],
          },
          {
            id: "component",
            labelName: "Component",
            setterType: "EVENT_TARGET_SELECT_SETTER",
            attrName: "widgetID",
            bindAttrName: "actionType",
            shown: (type) => type === "widget",
          },
          {
            id: "Method",
            labelName: "Method",
            setterType: "EVENT_WIDGET_METHOD_SELECT_SETTER",
            attrName: "widgetMethod",
            bindAttrName: "widgetID",
            shown: (widgetID) => !!widgetID,
          },
          {
            id: "Value",
            labelName: "Value",
            setterType: "INPUT_SETTER",
            attrName: "widgetTargetValue",
            bindAttrName: "widgetMethod",
            shown: (widgetMethod) => widgetMethod === "setValue",
          },
          {
            id: "disabled",
            labelName: "editor.inspect.setter_label.disabled",
            setterType: "DYNAMIC_SWITCH_SETTER",
            expectedType: VALIDATION_TYPES.BOOLEAN,
            attrName: "disabled",
            bindAttrName: "type",
            useCustomLayout: true,
            shown: (type) => type === "widget",
          },
          {
            id: "script",
            setterType: "INPUT_SETTER",
            attrName: "script",
            bindAttrName: "actionType",
            expectedType: VALIDATION_TYPES.STRING,
            shown: (type) => type === "script",
          },
          {
            id: "URL",
            labelName: "URL",
            setterType: "INPUT_SETTER",
            attrName: "url",
            bindAttrName: "actionType",
            expectedType: VALIDATION_TYPES.STRING,
            shown: (type) => type === "openUrl",
          },
          {
            id: "newTab",
            labelName: "New Tab",
            setterType: "DYNAMIC_SWITCH_SETTER",
            expectedType: VALIDATION_TYPES.BOOLEAN,
            attrName: "newTab",
            bindAttrName: "actionType",
            useCustomLayout: true,
            shown: (type) => type === "openUrl",
          },
          {
            id: "title",
            labelName: "Title",
            setterType: "INPUT_SETTER",
            attrName: "title",
            bindAttrName: "actionType",
            expectedType: VALIDATION_TYPES.STRING,
            shown: (type) => type === "showNotification",
          },
          {
            id: "description",
            labelName: "Description",
            setterType: "INPUT_SETTER",
            expectedType: VALIDATION_TYPES.STRING,
            attrName: "description",
            bindAttrName: "actionType",
            shown: (type) => type === "showNotification",
          },
          {
            id: "notification-type",
            labelName: "Type",
            setterType: "BASE_SELECT_SETTER",
            attrName: "notificationType",
            bindAttrName: "actionType",
            shown: (type) => type === "showNotification",
            options: [
              { label: "Success", value: "success" },
              { label: "Error", value: "error" },
              { label: "Warning", value: "warning" },
              { label: "Info", value: "info" },
            ],
          },
          {
            id: "duration",
            labelName: "Duration",
            setterType: "INPUT_SETTER",
            attrName: "duration",
            bindAttrName: "actionType",
            expectedType: VALIDATION_TYPES.NUMBER,
            shown: (type) => type === "showNotification",
          },
          {
            id: "enabled",
            labelName: "Only run when",
            labelDesc: "xxxxx",
            setterType: "INPUT_SETTER",
            expectedType: VALIDATION_TYPES.BOOLEAN,
            attrName: "enabled",
          },
        ],
      },
      {
        id: "upload-interaction-disabled",
        labelName: "editor.inspect.setter_label.disabled",
        attrName: "disabled",
        setterType: "INPUT_SETTER",
        placeholder: "{{false}}",
        expectedType: VALIDATION_TYPES.BOOLEAN,
      },
      {
        id: "upload-interaction-loading",
        labelName: "editor.inspect.setter_label.loading",
        attrName: "loading",
        setterType: "INPUT_SETTER",
        placeholder: "{{false}}",
        expectedType: VALIDATION_TYPES.BOOLEAN,
      },
    ],
  },
  {
    id: "upload-Adornments",
    groupName: "editor.inspect.setter_group.adornments",
    children: [
      {
        id: "upload-adornments-tooltip",
        labelName: "editor.inspect.setter_label.tooltip",
        attrName: "tooltipText",
        setterType: "INPUT_SETTER",
        expectedType: VALIDATION_TYPES.STRING,
      },
      {
        id: "upload-adornments-allowClear",
        labelName: "editor.inspect.setter_label.allow_clear",
        attrName: "allowClear",
        setterType: "DYNAMIC_SWITCH_SETTER",
        useCustomLayout: true,
        expectedType: VALIDATION_TYPES.BOOLEAN,
      },
    ],
  },
  {
    id: "upload-layout",
    groupName: "editor.inspect.setter_group.layout",
    children: [
      {
        id: "upload-layout-alignment",
        setterType: "RADIO_GROUP_SETTER",
        labelName: "editor.inspect.setter_label.align",
        attrName: "alignment",
        options: [
          {
            label: <HorizontalStartIcon />,
            value: "start",
          },
          {
            label: <HorizontalCenterIcon />,
            value: "center",
          },
          {
            label: <HorizontalEndIcon />,
            value: "end",
          },
          {
            label: <HorizontalFullIcon />,
            value: "fullWidth",
          },
        ],
      },
      {
        id: "upload-layout-hidden",
        labelName: "editor.inspect.setter_label.hidden",
        setterType: "DYNAMIC_SWITCH_SETTER",
        attrName: "hidden",
        placeholder: "false",
        useCustomLayout: true,
        expectedType: VALIDATION_TYPES.BOOLEAN,
      },
    ],
  },
  {
    id: `upload-style`,
    groupName: "editor.inspect.setter_group.style",
    children: [
      {
        id: "upload-style",
        setterType: "LIST_SETTER",
        labelName: "editor.inspect.setter_label.styles",
        attrName: "styles",
        useCustomLayout: true,
        childrenSetter: [
          {
            id: "upload-style-color",
            labelName: "editor.inspect.setter_label.theme_color",
            attrName: "colorScheme",
            setterType: "COLOR_PICKER_SETTER",
            defaultValue: "blue",
            options: colorSchemeOptions,
          },
        ],
      },
    ],
  },
]
