export enum ERROR_FLAG {
  // validate failed
  ERROR_FLAG_VALIDATE_ACCOUNT_FAILED = 1,
  ERROR_FLAG_VALIDATE_REQUEST_BODY_FAILED,
  ERROR_FLAG_VALIDATE_REQUEST_TOKEN_FAILED,
  ERROR_FLAG_VALIDATE_REQUEST_PARAM_FAILED,
  ERROR_FLAG_VALIDATE_VERIFICATION_CODE_FAILED,
  ERROR_FLAG_PARSE_REQUEST_BODY_FAILED,
  ERROR_FLAG_PARSE_REQUEST_URI_FAILED,
  ERROR_FLAG_PARSE_INVITE_LINK_HASH_FAILED,
  ERROR_FLAG_CAN_NOT_TRANSFER_OWNER_TO_PENDING_USER,
  ERROR_FLAG_CAN_NOT_REMOVE_OWNER_FROM_TEAM,
  ERROR_FLAG_SIGN_UP_EMAIL_MISMATCH,
  ERROR_FLAG_OWNER_ROLE_MUST_BE_TRANSFERED,
  ERROR_FLAG_PASSWORD_INVALIED,
  ERROR_FLAG_TEAM_MUST_TRANSFERED_BEFORE_USER_SUSPEND,
  ERROR_FLAG_INVITE_EMAIL_MISMATCH,

  // can not create
  ERROR_FLAG_CAN_NOT_CREATE_USER,
  ERROR_FLAG_CAN_NOT_CREATE_TEAM,
  ERROR_FLAG_CAN_NOT_CREATE_TEAM_MEMBER,
  ERROR_FLAG_CAN_NOT_CREATE_INVITE,
  ERROR_FLAG_CAN_NOT_CREATE_INVITATION_CODE,
  ERROR_FLAG_CAN_NOT_CREATE_DOMAIN,
  ERROR_FLAG_CAN_NOT_CREATE_ACTION,
  ERROR_FLAG_CAN_NOT_CREATE_RESOURCE,
  ERROR_FLAG_CAN_NOT_CREATE_APP,

  // can not get resource
  ERROR_FLAG_CAN_NOT_GET_USER,
  ERROR_FLAG_CAN_NOT_GET_TEAM,
  ERROR_FLAG_CAN_NOT_GET_TEAM_MEMBER,
  ERROR_FLAG_CAN_NOT_GET_INVITE,
  ERROR_FLAG_CAN_NOT_GET_INVITATION_CODE,
  ERROR_FLAG_CAN_NOT_GET_DOMAIN,
  ERROR_FLAG_CAN_NOT_GET_ACTION,
  ERROR_FLAG_CAN_NOT_GET_RESOURCE,
  ERROR_FLAG_CAN_NOT_GET_RESOURCE_META_INFO,
  ERROR_FLAG_CAN_NOT_GET_APP,
  ERROR_FLAG_CAN_NOT_GET_BUILDER_DESCRIPTION,

  // can not update resource
  ERROR_FLAG_CAN_NOT_UPDATE_USER,
  ERROR_FLAG_CAN_NOT_UPDATE_TEAM,
  ERROR_FLAG_CAN_NOT_UPDATE_TEAM_MEMBER,
  ERROR_FLAG_CAN_NOT_UPDATE_INVITE,
  ERROR_FLAG_CAN_NOT_UPDATE_INVITATION_CODE,
  ERROR_FLAG_CAN_NOT_UPDATE_DOMAIN,
  ERROR_FLAG_CAN_NOT_UPDATE_ACTION,
  ERROR_FLAG_CAN_NOT_UPDATE_RESOURCE,
  ERROR_FLAG_CAN_NOT_UPDATE_APP,

  // can not delete
  ERROR_FLAG_CAN_NOT_DELETE_USER,
  ERROR_FLAG_CAN_NOT_DELETE_TEAM,
  ERROR_FLAG_CAN_NOT_DELETE_TEAM_MEMBER,
  ERROR_FLAG_CAN_NOT_DELETE_INVITE,
  ERROR_FLAG_CAN_NOT_DELETE_INVITATION_CODE,
  ERROR_FLAG_CAN_NOT_DELETE_DOMAIN,
  ERROR_FLAG_CAN_NOT_DELETE_ACTION,
  ERROR_FLAG_CAN_NOT_DELETE_RESOURCE,
  ERROR_FLAG_CAN_NOT_DELETE_APP,

  // can not other operation
  ERROR_FLAG_CAN_NOT_CHECK_TEAM_MEMBER,
  ERROR_FLAG_CAN_NOT_DUPLICATE_APP,
  ERROR_FLAG_CAN_NOT_RELEASE_APP,
  ERROR_FLAG_CAN_NOT_TEST_RESOURCE_CONNECTION,

  // permission failed
  ERROR_FLAG_ACCESS_DENIED,
  ERROR_FLAG_TEAM_CLOSED_THE_PERMISSION,
  ERROR_FLAG_EMAIL_ALREADY_USED,
  ERROR_FLAG_EMAIL_HAS_BEEN_TAKEN,
  ERROR_FLAG_INVITATION_CODE_ALREADY_USED,
  ERROR_FLAG_INVITATION_LINK_UNAVALIABLE,
  ERROR_FLAG_TEAM_IDENTIFIER_HAS_BEEN_TAKEN,
  ERROR_FLAG_USER_ALREADY_JOINED_TEAM,
  ERROR_FLAG_SIGN_IN_FAILED,
  ERROR_FLAG_NO_SUCH_USER,

  // call resource failed
  ERROR_FLAG_SEND_EMAIL_FAILED,
  ERROR_FLAG_SEND_VERIFICATION_CODE_FAILED,
  ERROR_FLAG_CREATE_LINK_FAILED,
  ERROR_FLAG_CREATE_UPLOAD_URL_FAILED,
  ERROR_FLAG_EXECUTE_ACTION_FAILED,
  ERROR_FLAG_GENERATE_SQL_FAILED,

  // internal failed
  ERROR_FLAG_BUILD_TEAM_MEMBER_LIST_FAILED,
  ERROR_FLAG_BUILD_TEAM_CONFIG_FAILED,
  ERROR_FLAG_BUILD_TEAM_PERMISSION_FAILED,
  ERROR_FLAG_BUILD_USER_INFO_FAILED,
  ERROR_FLAG_BUILD_APP_CONFIG_FAILED,
  ERROR_FLAG_GENERATE_PASSWORD_FAILED,
}
