declare namespace NodeJS {
  interface ProcessEnv {
    readonly ILLA_API_BASE_URL: string
    readonly ILLA_BUILDER_URL: string
    readonly ILLA_CLOUD_URL: string
    readonly ILLA_MARKET_URL: string
    readonly ILLA_INSTANCE_ID: string
    readonly ILLA_APP_VERSION: string
    readonly ILLA_APP_ENV: string
    readonly ILLA_CLOUD_USER_EMAIL: string
    readonly ILLA_CLOUD_USER_PASSWORD: string
    readonly ILLA_CLOUD_TEAM_IDENTITY: string
    readonly ILLA_SUPABASE_KEY: string
    readonly ILLA_S3_ACL: string
    readonly ILLA_S3_REGION: string
    readonly ILLA_S3_BASEURL: string
    readonly ILLA_S3_BUCKETNAME: string
    readonly ILLA_S3_ACCESSKEYID: string
    readonly ILLA_S3_SECRETACCESSKEY: string
    readonly ILLA_NEON_HOST: string
    readonly ILLA_NEON_PORT: string
    readonly ILLA_NEON_DATABASENAME: string
    readonly ILLA_NEON_DATABASEPASSWORD: string
    readonly ILLA_NEON_DATABASEUSERNAME: string
    readonly ILLA_SMTP_HOST: string
    readonly ILLA_SMTP_PASSWORD: string
    readonly ILLA_SMTP_USERNAME: string
    readonly ILLA_SMTP_PORT: string
    readonly ILLA_TIDB_HOST: string
    readonly ILLA_TIDB_PORT: string
    readonly ILLA_TIDB_DATABASENAME: string
    readonly ILLA_TIDB_DATABASEPASSWORD: string
    readonly ILLA_TIDB_DATABASEUSERNAME: string
    readonly ILLA_MSSQL_HOST: string
    readonly ILLA_MSSQL_PORT: string
    readonly ILLA_MSSQL_PASSWORD: string
    readonly ILLA_MSSQL_USERNAME: string
    readonly ILLA_MSSQL_DATABASENAME: string
    readonly ILLA_MYSQL_HOST: string
    readonly ILLA_MYSQL_PORT: string
    readonly ILLA_MYSQL_DATABASENAME: string
    readonly ILLA_MYSQL_DATABASEPASSWORD: string
    readonly ILLA_MYSQL_DATABASEUSERNAME: string
    readonly ILLA_REDIS_HOST: string
    readonly ILLA_REDIS_PORT: string
    readonly ILLA_REDIS_DATABASEPASSWORD: string
    readonly ILLA_REDIS_DATABASEUSERNAME: string
    readonly ILLA_ORACLE_HOST: string
    readonly ILLA_ORACLE_NAME: string
    readonly ILLA_ORACLE_PORT: string
    readonly ILLA_ORACLE_PASSWORD: string
    readonly ILLA_ORACLE_USERNAME: string
    readonly ILLA_ORACLE_CONNECTIONTYPE: string
    readonly ILLA_COUCHDB_HOST: string
    readonly ILLA_COUCHDB_PORT: string
    readonly ILLA_COUCHDB_PASSWORD: string
    readonly ILLA_COUCHDB_USERNAME: string
    readonly ILLA_MARIADB_HOST: string
    readonly ILLA_MARIADB_PORT: string
    readonly ILLA_MARIADB_DATABASENAME: string
    readonly ILLA_MARIADB_DATABASEPASSWORD: string
    readonly ILLA_MARIADB_DATABASEUSERNAME: string
    readonly ILLA_RESTAPI_BASEURL: string
    readonly ILLA_RESTAPI_AUTHENTICATION: string
    readonly ILLA_APPWRITE_HOST: string
    readonly ILLA_APPWRITE_APIKEY: string
    readonly ILLA_APPWRITE_PROJECTID: string
    readonly ILLA_APPWRITE_DATABASEID: string
    readonly ILLA_FIREBASE_PROJECTID: string
    readonly ILLA_FIREBASE_DATABASEURL: string
    readonly ILLA_FIREBASE_PRIVATEKEY: string
    readonly ILLA_POSTGRESQL_HOST: string
    readonly ILLA_POSTGRESQL_PORT: string
    readonly ILLA_POSTGRESQL_DATABASENAME: string
    readonly ILLA_POSTGRESQL_DATABASEPASSWORD: string
    readonly ILLA_POSTGRESQL_DATABASEUSERNAME: string
    readonly ILLA_HUGGINGFACE_TOKEN: string
    readonly ILLA_GOOGLESHEETS_AUTHENTICATION: string
    readonly ILLA_GOOGLESHEETS_PRIVATEKEY: string
    readonly ILLA_ELASTICSEARCH_HOST: string
    readonly ILLA_ELASTICSEARCH_PORT: string
    readonly ILLA_ELASTICSEARCH_PASSWORD: string
    readonly ILLA_ELASTICSEARCH_USERNAME: string
  }
}
