import { PanelConfig } from "@/page/App/components/InspectPanel/interface"
import { VALIDATION_TYPES } from "@/utils/validationFactory"

const BASE_TYPE = "ACTION_TYPE"

export const EVENT_HANDLER_CONFIG: PanelConfig[] = [
  {
    id: `${BASE_TYPE}-interaction-success-event-handler`,
    attrName: "successEvents",
    labelName: "Success",
    // labelDesc: "xxxxx",
    setterType: "EVENT_HANDLER_SETTER",
    defaultValue: "success",
    useCustomLayout: true,
    childrenSetter: [
      {
        id: "event",
        labelName: "editor.inspect.setter_label.event",
        setterType: "BASE_SELECT_SETTER",
        attrName: "eventType",
        options: [{ label: "Success", value: "success" }],
      },
      {
        id: "action",
        labelName: "editor.inspect.setter_label.action",
        setterType: "EVENT_ACTION_SELECT_SETTER",
        attrName: "actionType",
        options: [
          {
            label: "editor.inspect.setter_label.trigger_query",
            value: "datasource",
          },
          {
            label: "editor.inspect.setter_label.control_component",
            value: "widget",
          },
          {
            label: "editor.inspect.setter_label.run_script",
            value: "script",
          },
          {
            label: "editor.inspect.setter_label.go_to_url",
            value: "openUrl",
          },
          {
            label: "editor.inspect.setter_label.show_notification",
            value: "showNotification",
          },
        ],
      },
      {
        id: "query",
        labelName: "Query",
        setterType: "BASE_SELECT_SETTER",
        attrName: "queryID",
        bindAttrName: "actionType",
        shown: (type) => type === "datasource",
      },
      {
        id: "component",
        labelName: "Component",
        setterType: "EVENT_TARGET_SELECT_SETTER",
        attrName: "widgetID",
        bindAttrName: "actionType",
        shown: (type) => type === "widget",
      },
      {
        id: "Method",
        labelName: "Method",
        setterType: "EVENT_WIDGET_METHOD_SELECT_SETTER",
        attrName: "widgetMethod",
        bindAttrName: "widgetID",
        shown: (widgetID) => !!widgetID,
      },
      {
        id: "Value",
        labelName: "Value",
        setterType: "INPUT_SETTER",
        attrName: "widgetTargetValue",
        bindAttrName: "widgetMethod",
        shown: (widgetMethod) => widgetMethod === "setValue",
      },
      {
        id: "imageUrl",
        labelName: "Value",
        setterType: "INPUT_SETTER",
        attrName: "widgetTargetValue",
        bindAttrName: "widgetMethod",
        shown: (widgetMethod) => widgetMethod === "setImageUrl",
      },
      {
        id: "disabled",
        labelName: "editor.inspect.setter_label.disabled",
        setterType: "DYNAMIC_SWITCH_SETTER",
        expectedType: VALIDATION_TYPES.BOOLEAN,
        attrName: "disabled",
        bindAttrName: "type",
        useCustomLayout: true,
        shown: (type) => type === "widget",
      },
      {
        id: "script",
        setterType: "INPUT_SETTER",
        attrName: "script",
        bindAttrName: "actionType",
        expectedType: VALIDATION_TYPES.STRING,
        shown: (type) => type === "script",
      },
      {
        id: "URL",
        labelName: "URL",
        setterType: "INPUT_SETTER",
        attrName: "url",
        bindAttrName: "actionType",
        expectedType: VALIDATION_TYPES.STRING,
        shown: (type) => type === "openUrl",
      },
      {
        id: "newTab",
        labelName: "New Tab",
        setterType: "DYNAMIC_SWITCH_SETTER",
        expectedType: VALIDATION_TYPES.BOOLEAN,
        attrName: "newTab",
        bindAttrName: "actionType",
        useCustomLayout: true,
        shown: (type) => type === "openUrl",
      },
      {
        id: "title",
        labelName: "Title",
        setterType: "INPUT_SETTER",
        attrName: "title",
        bindAttrName: "actionType",
        expectedType: VALIDATION_TYPES.STRING,
        shown: (type) => type === "showNotification",
      },
      {
        id: "description",
        labelName: "Description",
        setterType: "INPUT_SETTER",
        expectedType: VALIDATION_TYPES.STRING,
        attrName: "description",
        bindAttrName: "actionType",
        shown: (type) => type === "showNotification",
      },
      {
        id: "notification-type",
        labelName: "Type",
        setterType: "BASE_SELECT_SETTER",
        attrName: "notificationType",
        bindAttrName: "actionType",
        shown: (type) => type === "showNotification",
        options: [
          { label: "Success", value: "success" },
          { label: "Error", value: "error" },
          { label: "Warning", value: "warning" },
          { label: "Info", value: "info" },
        ],
      },
      {
        id: "duration",
        labelName: "Duration",
        setterType: "INPUT_SETTER",
        attrName: "duration",
        bindAttrName: "actionType",
        expectedType: VALIDATION_TYPES.NUMBER,
        shown: (type) => type === "showNotification",
      },
      {
        id: "enabled",
        labelName: "Only run when",
        // labelDesc: "xxxxx",
        setterType: "INPUT_SETTER",
        expectedType: VALIDATION_TYPES.BOOLEAN,
        attrName: "enabled",
      },
    ],
  },
  {
    id: `${BASE_TYPE}-interaction-failed-event-handler`,
    attrName: "failedEvents",
    labelName: "Failed",
    // labelDesc: "xxxxx",
    setterType: "EVENT_HANDLER_SETTER",
    defaultValue: "failed",
    useCustomLayout: true,
    childrenSetter: [
      {
        id: "event",
        labelName: "editor.inspect.setter_label.event",
        setterType: "BASE_SELECT_SETTER",
        attrName: "eventType",
        options: [{ label: "Failed", value: "failed" }],
      },
      {
        id: "action",
        labelName: "editor.inspect.setter_label.action",
        setterType: "EVENT_ACTION_SELECT_SETTER",
        attrName: "actionType",
        options: [
          {
            label: "editor.inspect.setter_label.trigger_query",
            value: "datasource",
          },
          {
            label: "editor.inspect.setter_label.control_component",
            value: "widget",
          },
          {
            label: "editor.inspect.setter_label.run_script",
            value: "script",
          },
          {
            label: "editor.inspect.setter_label.go_to_url",
            value: "openUrl",
          },
          {
            label: "editor.inspect.setter_label.show_notification",
            value: "showNotification",
          },
        ],
      },
      {
        id: "query",
        labelName: "Query",
        setterType: "BASE_SELECT_SETTER",
        attrName: "queryID",
        bindAttrName: "actionType",
        shown: (type) => type === "datasource",
      },
      {
        id: "component",
        labelName: "Component",
        setterType: "EVENT_TARGET_SELECT_SETTER",
        attrName: "widgetID",
        bindAttrName: "actionType",
        shown: (type) => type === "widget",
      },
      {
        id: "Method",
        labelName: "Method",
        setterType: "EVENT_WIDGET_METHOD_SELECT_SETTER",
        attrName: "widgetMethod",
        bindAttrName: "widgetID",
        shown: (widgetID) => !!widgetID,
      },
      {
        id: "Value",
        labelName: "Value",
        setterType: "INPUT_SETTER",
        attrName: "widgetTargetValue",
        bindAttrName: "widgetMethod",
        shown: (widgetMethod) => widgetMethod === "setValue",
      },
      {
        id: "imageUrl",
        labelName: "Value",
        setterType: "INPUT_SETTER",
        attrName: "widgetTargetValue",
        bindAttrName: "widgetMethod",
        shown: (widgetMethod) => widgetMethod === "setImageUrl",
      },
      {
        id: "disabled",
        labelName: "editor.inspect.setter_label.disabled",
        setterType: "DYNAMIC_SWITCH_SETTER",
        expectedType: VALIDATION_TYPES.BOOLEAN,
        attrName: "disabled",
        bindAttrName: "type",
        useCustomLayout: true,
        shown: (type) => type === "widget",
      },
      {
        id: "script",
        setterType: "INPUT_SETTER",
        attrName: "script",
        bindAttrName: "actionType",
        expectedType: VALIDATION_TYPES.STRING,
        shown: (type) => type === "script",
      },
      {
        id: "URL",
        labelName: "URL",
        setterType: "INPUT_SETTER",
        attrName: "url",
        bindAttrName: "actionType",
        expectedType: VALIDATION_TYPES.STRING,
        shown: (type) => type === "openUrl",
      },
      {
        id: "newTab",
        labelName: "New Tab",
        setterType: "DYNAMIC_SWITCH_SETTER",
        expectedType: VALIDATION_TYPES.BOOLEAN,
        attrName: "newTab",
        bindAttrName: "actionType",
        useCustomLayout: true,
        shown: (type) => type === "openUrl",
      },
      {
        id: "title",
        labelName: "Title",
        setterType: "INPUT_SETTER",
        attrName: "title",
        bindAttrName: "actionType",
        expectedType: VALIDATION_TYPES.STRING,
        shown: (type) => type === "showNotification",
      },
      {
        id: "description",
        labelName: "Description",
        setterType: "INPUT_SETTER",
        expectedType: VALIDATION_TYPES.STRING,
        attrName: "description",
        bindAttrName: "actionType",
        shown: (type) => type === "showNotification",
      },
      {
        id: "notification-type",
        labelName: "Type",
        setterType: "BASE_SELECT_SETTER",
        attrName: "notificationType",
        bindAttrName: "actionType",
        shown: (type) => type === "showNotification",
        options: [
          { label: "Success", value: "success" },
          { label: "Error", value: "error" },
          { label: "Warning", value: "warning" },
          { label: "Info", value: "info" },
        ],
      },
      {
        id: "duration",
        labelName: "Duration",
        setterType: "INPUT_SETTER",
        attrName: "duration",
        bindAttrName: "actionType",
        expectedType: VALIDATION_TYPES.NUMBER,
        shown: (type) => type === "showNotification",
      },
      {
        id: "enabled",
        labelName: "Only run when",
        // labelDesc: "xxxxx",
        setterType: "INPUT_SETTER",
        expectedType: VALIDATION_TYPES.BOOLEAN,
        attrName: "enabled",
      },
    ],
  },
]
