export const MongoDbActionList = [
  "aggregate",
  "bulkWrite",
  "count",
  "deleteMany",
  "deleteOne",
  "distinct",
  "find",
  "findOne",
  "findOneAndUpdate",
  "insertOne",
  "insertMany",
  "listCollections",
  "updateMany",
  "updateOne",
  "command",
]
